### ISSUE TITLE
Compat issues with BYG

### ISSUE THREAD

**Issue by Cluelesshobo** [P3NG00/MoreBookshelvesFabricMod#2]
"Oh The Biomes You'll Go" Enchanting tables stop working correctly with this mod installed only showing 8 as the max enchant instead of 30.

Also the mod appears to affect console outputs on a dedicated server like, _menu.loading_ instead of _Preparing World_ etc.

**Comment by P3NG00** [comment]
I've posted a fixed version (0.0.1) on my CurseForge page [here](https://www.curseforge.com/minecraft/mc-mods/bookshelving/files/3096662)!

**Comment by P3NG00** [comment]
I'm closing this.

I was using an incorrect method of overriding Minecraft's naming. the 'menu.loading' and whatnot should be fixed in 0.0.1.

The other issue regarding the 'Oh The Biomes You'll Go' enchanting tables not working is an issue that may not be able to be resolved if both of our mods are overriding each other.
